# Generated by Django 3.0 on 2019-12-09 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Squirrel',
            fields=[
                ('Latitude', models.FloatField()),
                ('Longitude', models.FloatField()),
                ('Unique_Squirrel_ID', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('Shift', models.CharField(choices=[('AM', 'AM'), ('PM', 'PM')], max_length=2)),
                ('Date', models.IntegerField()),
                ('Age', models.CharField(blank=True, choices=[('', '----'), ('Adult', 'Adult'), ('Juvenile', 'Juvenile'), ('?', 'Unknown')], max_length=10)),
                ('Primary_Fur_Color', models.CharField(blank=True, max_length=30)),
                ('Location', models.CharField(blank=True, max_length=30)),
                ('Specific_Location', models.CharField(blank=True, max_length=100)),
                ('Running', models.CharField(choices=[('true', 'True'), ('false', 'False')], max_length=10)),
                ('Chasing', models.CharField(choices=[('true', 'True'), ('false', 'False')], max_length=10)),
                ('Climbing', models.CharField(choices=[('true', 'True'), ('false', 'False')], max_length=10)),
                ('Eating', models.CharField(choices=[('true', 'True'), ('false', 'False')], max_length=10)),
                ('Foraging', models.CharField(choices=[('true', 'True'), ('false', 'False')], max_length=10)),
                ('Other_Activities', models.CharField(blank=True, max_length=100)),
                ('Kuks', models.CharField(choices=[('true', 'True'), ('false', 'False')], max_length=10)),
                ('Quaas', models.CharField(choices=[('true', 'True'), ('false', 'False')], max_length=10)),
                ('Moans', models.CharField(choices=[('true', 'True'), ('false', 'False')], max_length=10)),
                ('Tail_flags', models.CharField(choices=[('true', 'True'), ('false', 'False')], max_length=10)),
                ('Tail_twitches', models.CharField(choices=[('true', 'True'), ('false', 'False')], max_length=10)),
                ('Approaches', models.CharField(choices=[('true', 'True'), ('false', 'False')], max_length=10)),
                ('Indifferent', models.CharField(choices=[('true', 'True'), ('false', 'False')], max_length=10)),
                ('Runs_from', models.CharField(choices=[('true', 'True'), ('false', 'False')], max_length=10)),
            ],
        ),
    ]
